/**
 * scripts/migrate-farms.js
 * Extracts farm data from contracts (contratos), creates Fazenda records
 * using a composite key (nome + proprietario + cidade) for deduplication,
 * and links contracts to their corresponding fazenda.
 *
 * Runs at container startup — idempotent (safe to run multiple times).
 * On each run it resets all fazenda links and re-creates them from scratch
 * to ensure correctness.
 */
const { PrismaClient } = require("@prisma/client");

function normalizeStr(str) {
  if (!str) return "";
  return str
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

function compositeKey(contrato) {
  return [
    normalizeStr(contrato.nomeFazenda),
    normalizeStr(contrato.proprietario),
    normalizeStr(contrato.cidade),
  ].join("|");
}

async function main() {
  const prisma = new PrismaClient();
  try {
    // 1. Reset: unlink all contracts and delete all fazendas
    //    (fazendas are auto-generated by this script, safe to recreate)
    const allContracts = await prisma.contrato.findMany();
    const linkedCount = allContracts.filter((c) => c.fazendaId).length;

    if (linkedCount > 0) {
      await prisma.contrato.updateMany({
        where: { fazendaId: { not: null } },
        data: { fazendaId: null },
      });
      console.log(`>>> Fazendas: ${linkedCount} contrato(s) desvinculado(s).`);
    }

    const deletedFazendas = await prisma.fazenda.deleteMany();
    if (deletedFazendas.count > 0) {
      console.log(
        `>>> Fazendas: ${deletedFazendas.count} fazenda(s) antiga(s) removida(s).`
      );
    }

    // 2. Group contracts by composite key (nome + proprietario + cidade)
    const contracts = await prisma.contrato.findMany();

    if (contracts.length === 0) {
      console.log(">>> Fazendas: nenhum contrato encontrado. OK.");
      return;
    }

    const farmGroups = new Map();

    for (const contrato of contracts) {
      const key = compositeKey(contrato);
      if (!farmGroups.has(key)) {
        farmGroups.set(key, []);
      }
      farmGroups.get(key).push(contrato);
    }

    let created = 0;
    let linked = 0;

    for (const [, contratos] of farmGroups.entries()) {
      const source = contratos[0];

      // Create a new Fazenda for this group
      const fazenda = await prisma.fazenda.create({
        data: {
          nome: source.nomeFazenda,
          proprietario: source.proprietario,
          comunidade: source.comunidade,
          cidade: source.cidade,
          estado: source.estado,
          areaHectares: source.areaHectares,
          observacoes: source.observacoes,
        },
      });
      created++;

      // Link all contracts in this group to the fazenda
      for (const contrato of contratos) {
        await prisma.contrato.update({
          where: { id: contrato.id },
          data: { fazendaId: fazenda.id },
        });
        linked++;
      }
    }

    console.log(
      `>>> Fazendas: migração concluída — ${created} criada(s), ${linked} contrato(s) vinculado(s).`
    );
  } catch (err) {
    console.error(">>> Erro na migração de fazendas:", err.message);
  } finally {
    await prisma.$disconnect();
  }
}

main();
